// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/mao360/saga/order/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *OrderRepository) GetByID(ctx context.Context, id string) (domain.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type OrderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *OrderRepository_Expecter) GetByID(ctx interface{}, id interface{}) *OrderRepository_GetByID_Call {
	return &OrderRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *OrderRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *OrderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetByID_Call) Return(_a0 domain.Order, _a1 error) *OrderRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (domain.Order, error)) *OrderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, order
func (_m *OrderRepository) Save(ctx context.Context, order domain.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type OrderRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - order domain.Order
func (_e *OrderRepository_Expecter) Save(ctx interface{}, order interface{}) *OrderRepository_Save_Call {
	return &OrderRepository_Save_Call{Call: _e.mock.On("Save", ctx, order)}
}

func (_c *OrderRepository_Save_Call) Run(run func(ctx context.Context, order domain.Order)) *OrderRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Order))
	})
	return _c
}

func (_c *OrderRepository_Save_Call) Return(_a0 error) *OrderRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_Save_Call) RunAndReturn(run func(context.Context, domain.Order) error) *OrderRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
