// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/mao360/saga/order/internal/domain"
	mock "github.com/stretchr/testify/mock"

	postgres "github.com/mao360/saga/order/internal/platform/postgres"
)

// OutboxEnqueuer is an autogenerated mock type for the OutboxEnqueuer type
type OutboxEnqueuer struct {
	mock.Mock
}

type OutboxEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *OutboxEnqueuer) EXPECT() *OutboxEnqueuer_Expecter {
	return &OutboxEnqueuer_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function with given fields: ctx, q, msg
func (_m *OutboxEnqueuer) Enqueue(ctx context.Context, q postgres.DBTX, msg domain.OutboxMessage) error {
	ret := _m.Called(ctx, q, msg)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, postgres.DBTX, domain.OutboxMessage) error); ok {
		r0 = rf(ctx, q, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OutboxEnqueuer_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type OutboxEnqueuer_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - q postgres.DBTX
//   - msg domain.OutboxMessage
func (_e *OutboxEnqueuer_Expecter) Enqueue(ctx interface{}, q interface{}, msg interface{}) *OutboxEnqueuer_Enqueue_Call {
	return &OutboxEnqueuer_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, q, msg)}
}

func (_c *OutboxEnqueuer_Enqueue_Call) Run(run func(ctx context.Context, q postgres.DBTX, msg domain.OutboxMessage)) *OutboxEnqueuer_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(postgres.DBTX), args[2].(domain.OutboxMessage))
	})
	return _c
}

func (_c *OutboxEnqueuer_Enqueue_Call) Return(_a0 error) *OutboxEnqueuer_Enqueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OutboxEnqueuer_Enqueue_Call) RunAndReturn(run func(context.Context, postgres.DBTX, domain.OutboxMessage) error) *OutboxEnqueuer_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewOutboxEnqueuer creates a new instance of OutboxEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxEnqueuer {
	mock := &OutboxEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
