// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/mao360/saga/order/internal/domain"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	postgres "github.com/mao360/saga/order/internal/platform/postgres"
)

// SagaStateRepository is an autogenerated mock type for the SagaStateRepository type
type SagaStateRepository struct {
	mock.Mock
}

type SagaStateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SagaStateRepository) EXPECT() *SagaStateRepository_Expecter {
	return &SagaStateRepository_Expecter{mock: &_m.Mock}
}

// LockState provides a mock function with given fields: ctx, tx, sagaID
func (_m *SagaStateRepository) LockState(ctx context.Context, tx pgx.Tx, sagaID string) (domain.SagaState, error) {
	ret := _m.Called(ctx, tx, sagaID)

	if len(ret) == 0 {
		panic("no return value specified for LockState")
	}

	var r0 domain.SagaState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (domain.SagaState, error)); ok {
		return rf(ctx, tx, sagaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) domain.SagaState); ok {
		r0 = rf(ctx, tx, sagaID)
	} else {
		r0 = ret.Get(0).(domain.SagaState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, sagaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SagaStateRepository_LockState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockState'
type SagaStateRepository_LockState_Call struct {
	*mock.Call
}

// LockState is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - sagaID string
func (_e *SagaStateRepository_Expecter) LockState(ctx interface{}, tx interface{}, sagaID interface{}) *SagaStateRepository_LockState_Call {
	return &SagaStateRepository_LockState_Call{Call: _e.mock.On("LockState", ctx, tx, sagaID)}
}

func (_c *SagaStateRepository_LockState_Call) Run(run func(ctx context.Context, tx pgx.Tx, sagaID string)) *SagaStateRepository_LockState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(string))
	})
	return _c
}

func (_c *SagaStateRepository_LockState_Call) Return(_a0 domain.SagaState, _a1 error) *SagaStateRepository_LockState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SagaStateRepository_LockState_Call) RunAndReturn(run func(context.Context, pgx.Tx, string) (domain.SagaState, error)) *SagaStateRepository_LockState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInventoryStatus provides a mock function with given fields: ctx, q, sagaID, status
func (_m *SagaStateRepository) UpdateInventoryStatus(ctx context.Context, q postgres.DBTX, sagaID string, status string) error {
	ret := _m.Called(ctx, q, sagaID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInventoryStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, postgres.DBTX, string, string) error); ok {
		r0 = rf(ctx, q, sagaID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SagaStateRepository_UpdateInventoryStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInventoryStatus'
type SagaStateRepository_UpdateInventoryStatus_Call struct {
	*mock.Call
}

// UpdateInventoryStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - q postgres.DBTX
//   - sagaID string
//   - status string
func (_e *SagaStateRepository_Expecter) UpdateInventoryStatus(ctx interface{}, q interface{}, sagaID interface{}, status interface{}) *SagaStateRepository_UpdateInventoryStatus_Call {
	return &SagaStateRepository_UpdateInventoryStatus_Call{Call: _e.mock.On("UpdateInventoryStatus", ctx, q, sagaID, status)}
}

func (_c *SagaStateRepository_UpdateInventoryStatus_Call) Run(run func(ctx context.Context, q postgres.DBTX, sagaID string, status string)) *SagaStateRepository_UpdateInventoryStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(postgres.DBTX), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *SagaStateRepository_UpdateInventoryStatus_Call) Return(_a0 error) *SagaStateRepository_UpdateInventoryStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SagaStateRepository_UpdateInventoryStatus_Call) RunAndReturn(run func(context.Context, postgres.DBTX, string, string) error) *SagaStateRepository_UpdateInventoryStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentStatus provides a mock function with given fields: ctx, q, sagaID, status
func (_m *SagaStateRepository) UpdatePaymentStatus(ctx context.Context, q postgres.DBTX, sagaID string, status string) error {
	ret := _m.Called(ctx, q, sagaID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, postgres.DBTX, string, string) error); ok {
		r0 = rf(ctx, q, sagaID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SagaStateRepository_UpdatePaymentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentStatus'
type SagaStateRepository_UpdatePaymentStatus_Call struct {
	*mock.Call
}

// UpdatePaymentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - q postgres.DBTX
//   - sagaID string
//   - status string
func (_e *SagaStateRepository_Expecter) UpdatePaymentStatus(ctx interface{}, q interface{}, sagaID interface{}, status interface{}) *SagaStateRepository_UpdatePaymentStatus_Call {
	return &SagaStateRepository_UpdatePaymentStatus_Call{Call: _e.mock.On("UpdatePaymentStatus", ctx, q, sagaID, status)}
}

func (_c *SagaStateRepository_UpdatePaymentStatus_Call) Run(run func(ctx context.Context, q postgres.DBTX, sagaID string, status string)) *SagaStateRepository_UpdatePaymentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(postgres.DBTX), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *SagaStateRepository_UpdatePaymentStatus_Call) Return(_a0 error) *SagaStateRepository_UpdatePaymentStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SagaStateRepository_UpdatePaymentStatus_Call) RunAndReturn(run func(context.Context, postgres.DBTX, string, string) error) *SagaStateRepository_UpdatePaymentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewSagaStateRepository creates a new instance of SagaStateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSagaStateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SagaStateRepository {
	mock := &SagaStateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
