// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SagaMetrics is an autogenerated mock type for the SagaMetrics type
type SagaMetrics struct {
	mock.Mock
}

type SagaMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *SagaMetrics) EXPECT() *SagaMetrics_Expecter {
	return &SagaMetrics_Expecter{mock: &_m.Mock}
}

// ObserveSagaFinished provides a mock function with given fields: status, d
func (_m *SagaMetrics) ObserveSagaFinished(status string, d time.Duration) {
	_m.Called(status, d)
}

// SagaMetrics_ObserveSagaFinished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveSagaFinished'
type SagaMetrics_ObserveSagaFinished_Call struct {
	*mock.Call
}

// ObserveSagaFinished is a helper method to define mock.On call
//   - status string
//   - d time.Duration
func (_e *SagaMetrics_Expecter) ObserveSagaFinished(status interface{}, d interface{}) *SagaMetrics_ObserveSagaFinished_Call {
	return &SagaMetrics_ObserveSagaFinished_Call{Call: _e.mock.On("ObserveSagaFinished", status, d)}
}

func (_c *SagaMetrics_ObserveSagaFinished_Call) Run(run func(status string, d time.Duration)) *SagaMetrics_ObserveSagaFinished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *SagaMetrics_ObserveSagaFinished_Call) Return() *SagaMetrics_ObserveSagaFinished_Call {
	_c.Call.Return()
	return _c
}

func (_c *SagaMetrics_ObserveSagaFinished_Call) RunAndReturn(run func(string, time.Duration)) *SagaMetrics_ObserveSagaFinished_Call {
	_c.Run(run)
	return _c
}

// NewSagaMetrics creates a new instance of SagaMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSagaMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *SagaMetrics {
	mock := &SagaMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
