// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SagaCreator is an autogenerated mock type for the SagaCreator type
type SagaCreator struct {
	mock.Mock
}

type SagaCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *SagaCreator) EXPECT() *SagaCreator_Expecter {
	return &SagaCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sagaID, orderID
func (_m *SagaCreator) Create(ctx context.Context, sagaID string, orderID string) error {
	ret := _m.Called(ctx, sagaID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sagaID, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SagaCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SagaCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sagaID string
//   - orderID string
func (_e *SagaCreator_Expecter) Create(ctx interface{}, sagaID interface{}, orderID interface{}) *SagaCreator_Create_Call {
	return &SagaCreator_Create_Call{Call: _e.mock.On("Create", ctx, sagaID, orderID)}
}

func (_c *SagaCreator_Create_Call) Run(run func(ctx context.Context, sagaID string, orderID string)) *SagaCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SagaCreator_Create_Call) Return(_a0 error) *SagaCreator_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SagaCreator_Create_Call) RunAndReturn(run func(context.Context, string, string) error) *SagaCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewSagaCreator creates a new instance of SagaCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSagaCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *SagaCreator {
	mock := &SagaCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}