// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/mao360/saga/order/internal/domain"
	mock "github.com/stretchr/testify/mock"

	postgres "github.com/mao360/saga/order/internal/platform/postgres"
)

// SagaOrderRepository is an autogenerated mock type for the SagaOrderRepository type
type SagaOrderRepository struct {
	mock.Mock
}

type SagaOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SagaOrderRepository) EXPECT() *SagaOrderRepository_Expecter {
	return &SagaOrderRepository_Expecter{mock: &_m.Mock}
}

// GetByIDTx provides a mock function with given fields: ctx, q, id
func (_m *SagaOrderRepository) GetByIDTx(ctx context.Context, q postgres.DBTX, id string) (domain.Order, error) {
	ret := _m.Called(ctx, q, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDTx")
	}

	var r0 domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, postgres.DBTX, string) (domain.Order, error)); ok {
		return rf(ctx, q, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, postgres.DBTX, string) domain.Order); ok {
		r0 = rf(ctx, q, id)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, postgres.DBTX, string) error); ok {
		r1 = rf(ctx, q, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SagaOrderRepository_GetByIDTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDTx'
type SagaOrderRepository_GetByIDTx_Call struct {
	*mock.Call
}

// GetByIDTx is a helper method to define mock.On call
//   - ctx context.Context
//   - q postgres.DBTX
//   - id string
func (_e *SagaOrderRepository_Expecter) GetByIDTx(ctx interface{}, q interface{}, id interface{}) *SagaOrderRepository_GetByIDTx_Call {
	return &SagaOrderRepository_GetByIDTx_Call{Call: _e.mock.On("GetByIDTx", ctx, q, id)}
}

func (_c *SagaOrderRepository_GetByIDTx_Call) Run(run func(ctx context.Context, q postgres.DBTX, id string)) *SagaOrderRepository_GetByIDTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(postgres.DBTX), args[2].(string))
	})
	return _c
}

func (_c *SagaOrderRepository_GetByIDTx_Call) Return(_a0 domain.Order, _a1 error) *SagaOrderRepository_GetByIDTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SagaOrderRepository_GetByIDTx_Call) RunAndReturn(run func(context.Context, postgres.DBTX, string) (domain.Order, error)) *SagaOrderRepository_GetByIDTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, q, orderID, status
func (_m *SagaOrderRepository) UpdateStatus(ctx context.Context, q postgres.DBTX, orderID string, status string) error {
	ret := _m.Called(ctx, q, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, postgres.DBTX, string, string) error); ok {
		r0 = rf(ctx, q, orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SagaOrderRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type SagaOrderRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - q postgres.DBTX
//   - orderID string
//   - status string
func (_e *SagaOrderRepository_Expecter) UpdateStatus(ctx interface{}, q interface{}, orderID interface{}, status interface{}) *SagaOrderRepository_UpdateStatus_Call {
	return &SagaOrderRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, q, orderID, status)}
}

func (_c *SagaOrderRepository_UpdateStatus_Call) Run(run func(ctx context.Context, q postgres.DBTX, orderID string, status string)) *SagaOrderRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(postgres.DBTX), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *SagaOrderRepository_UpdateStatus_Call) Return(_a0 error) *SagaOrderRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SagaOrderRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, postgres.DBTX, string, string) error) *SagaOrderRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewSagaOrderRepository creates a new instance of SagaOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSagaOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SagaOrderRepository {
	mock := &SagaOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
