// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// TxRunner is an autogenerated mock type for the TxRunner type
type TxRunner struct {
	mock.Mock
}

type TxRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *TxRunner) EXPECT() *TxRunner_Expecter {
	return &TxRunner_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: ctx, fn
func (_m *TxRunner) Do(ctx context.Context, fn func(pgx.Tx) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(pgx.Tx) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxRunner_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type TxRunner_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(pgx.Tx) error
func (_e *TxRunner_Expecter) Do(ctx interface{}, fn interface{}) *TxRunner_Do_Call {
	return &TxRunner_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *TxRunner_Do_Call) Run(run func(ctx context.Context, fn func(pgx.Tx) error)) *TxRunner_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(pgx.Tx) error))
	})
	return _c
}

func (_c *TxRunner_Do_Call) Return(_a0 error) *TxRunner_Do_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxRunner_Do_Call) RunAndReturn(run func(context.Context, func(pgx.Tx) error) error) *TxRunner_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewTxRunner creates a new instance of TxRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxRunner {
	mock := &TxRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
